default: &default
  adapter: postgresql
  encoding: unicode
  username: etg
  password: immortal
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: basic_auth_development

test:
  <<: *default
  database: basic_auth_test

production:
  <<: *default
  database: basic_auth_production
  username: basic_auth
  password: <%= ENV["BASIC_AUTH_DATABASE_PASSWORD"] %>
